nome = input('Digite o nome do cliente: ')
y = input('Digite o dia de vencimento: ') 
z = input('Digite o mês de vencimento: ')
valor = input('Digite o valor da fatura: ')
print('Olá,',nome)
print('A sua fatura com vencimento em',y,'de',z,'no valor de R$',valor,'está fechada.')
